// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqzHPM8k1bK0q-l07PqB4w5_COttkAuGE',
    appId: '1:1003345878125:web:9a3eaa90881bb88f5e7364',
    messagingSenderId: '1003345878125',
    projectId: 'my-chatt-c75a7',
    authDomain: 'my-chatt-c75a7.firebaseapp.com',
    storageBucket: 'my-chatt-c75a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCzQmvwWyCiAslUDWipthbdL4m_zbRb9Y',
    appId: '1:1003345878125:android:35973599cf28e6ed5e7364',
    messagingSenderId: '1003345878125',
    projectId: 'my-chatt-c75a7',
    storageBucket: 'my-chatt-c75a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxfK4qTMeJOVAVomPyzH_ppO2PexWQLKI',
    appId: '1:1003345878125:ios:e2c6b1532d426e5f5e7364',
    messagingSenderId: '1003345878125',
    projectId: 'my-chatt-c75a7',
    storageBucket: 'my-chatt-c75a7.appspot.com',
    androidClientId: '1003345878125-onqhmtb8dhkbc8248hg63cpfc1fp7dd7.apps.googleusercontent.com',
    iosClientId: '1003345878125-uq1fto9ecunfql8a1l847aja4gb8j9of.apps.googleusercontent.com',
    iosBundleId: 'com.mychatt.myChattApp',
  );

}